name: csmambasr_train_ucmerced_x2

model_type: CSMambaSRModel
scale: 2
num_gpu: 1
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: UCMerced-train
    type: PairedImageDataset
    dataroot_gt: ../datasets/UCMerced/train/train_HR
    dataroot_lq: ../datasets/UCMerced/train/train_LR_bicubic/x2
    #filename_tmpl: '{}x2'
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 1
    batch_size_per_gpu: 4
    prefetch_mode: ~

  val:
    name: UCMerced-val
    type: PairedImageDataset
    dataroot_gt: ../datasets/UCMerced/val/val_HR
    dataroot_lq: ../datasets/UCMerced/val/val_LR_bicubic/x2
    filename_tmpl: '{}'
    io_backend:
      type: disk

# network structures
network_g:
  type: CSMambaSR
  upscale: 2
  in_chans: 3
  img_size: 64
  img_range: 1.
  d_state: 16
  depths: [6, 6, 6, 6, 6, 6]
  # depths: [4, 4, 4, 4, 4, 4]
  embed_dim: 180
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'
  cross_scale: 0.4

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [29532, 59063, 88596] # total=945 batch_size=4, 500epoch
    gamma: 0.5

  total_iter: 118125 # total=945 batch_size=4, 500epoch

  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true

# logging settings
logger:
  print_freq: 200
  # save_checkpoint_freq: !!float 315
  save_checkpoint_freq: !!float 5e3

  # save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500